XBUILD=/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
PROJECT_ROOT=.
PROJECT=$(PROJECT_ROOT)/Lua_iPhone.xcodeproj
TARGET=Lua_iPhone

all: libLua52iOS.a

libLua52-i386.a:
	$(XBUILD) -project $(PROJECT) -target $(TARGET) -sdk iphonesimulator -configuration Release clean build
	-mv $(PROJECT_ROOT)/build/Release-iphonesimulator/libLua_iPhone.a $@

libLua52-armv7.a:
	$(XBUILD) -project $(PROJECT) -target $(TARGET) -sdk iphoneos -arch armv7 -configuration Release clean build
	-mv $(PROJECT_ROOT)/build/Release-iphoneos/libLua_iPhone.a $@

libLua52-armv7s.a:
	$(XBUILD) -project $(PROJECT) -target $(TARGET) -sdk iphoneos -arch armv7s -configuration Release clean build
	-mv $(PROJECT_ROOT)/build/Release-iphoneos/libLua_iPhone.a $@

libLua52iOS.a: libLua52-i386.a libLua52-armv7.a libLua52-armv7s.a
	lipo -create -output $@ $^

clean:
	-rm -f *.a
